name: Pull Request Checks

on: [pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install yarn"
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
    - name: "Cache: node_modules"
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-${{ env.cache-name }}-
          ${{ runner.OS }}-node-
    - name: "Init: Install dependencies"
      run: |
        yarn install
    - name: "Test: Run test suite"
      run: |
        yarn test
    - name: "Test: Code linting"
      run: |
        yarn test:lint
