name: Deployments

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  pages: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  containers:
    name: ${{ matrix.context }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [resonator, medium]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: node
        uses: actions/setup-node@v3

      - name: buildx
        uses: docker/setup-buildx-action@v2

      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}-${{ matrix.context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: publish
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_NAME }}
          location: gke.cluster-rcf2
          name: dorothy-${{ matrix.context }}
          image: ghcr.io/${{ github.repository }}-${{ matrix.context }}
          minReplicas: 1
          maxReplicas: 20
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
